import type { Dict } from "./types";

export const es: Dict = {
  meta: {
    title: "Visor EVTX online — abrir archivos .evtx sin subirlos",
    description:
      "Un archivo .evtx es un registro de eventos de Windows. Ábrelo gratis en el navegador — sin subirlo ni instalar nada — filtra y exporta a CSV, TXT, JSON o XML.",
    siteName: "EVTX parser",
  },
  home: {
    heading: "EVTX parser",
    headline: "EVTX parser — visor de registros de Windows en el navegador",
    intro:
      "Suelta un registro de eventos .evtx de Windows. El análisis se ejecuta en tu navegador mediante WebAssembly — no se sube nada.",
    featuredHeading: "Guías destacadas",
    dropArea: "Suelta un .evtx aquí o haz clic para elegir",
    privacyNote: "Los archivos se quedan en tu dispositivo. Análisis 100 % en el cliente.",
    heroTag: "Código abierto · 100 % en tu navegador",
    heroCtaOpen: "Abrir un archivo .evtx",
    heroCtaGithub: "Ver en GitHub",
    footerTagline: "Análisis forense de registros de Windows, íntegramente en tu navegador.",
    statHunts: "reglas de hunting integradas",
    statUploaded: "bytes subidos",
    statEngine: "parser compilado a WebAssembly",
    statLocales: "idiomas",
    worksWith: "Lee cualquier canal que recopiles",
    featuresEyebrow: "Hecho para respuesta a incidentes",
    featuresHeading: "Del .evtx en bruto a hallazgos en minutos",
    featuresIntro: "Todo lo que un analista DFIR necesita, sin instalar el Visor de eventos, Python ni un SIEM.",
    ctaHeading: "Tu próxima investigación empieza soltando un archivo.",
    ctaBody: "Gratis, de código abierto y privado por diseño. Sin cuenta, sin subida, sin instalación.",
    features: [
      { title: "Hunts al abrir", body: "{n} detecciones — Kerberoasting, borrado de registros, cradles de PowerShell, servicios nuevos, fuerza bruta — se ejecutan al cargar el archivo." },
      { title: "Un lenguaje de consulta para analistas", body: "Campo:valor, comodines, comillas y negación sobre cada campo EventData, con facetas al instante y orden por valores raros." },
      { title: "Pivotes en un clic", body: "Salta de cualquier evento al mismo Logon ID, GUID de proceso, proceso padre o a una ventana de ±5 minutos." },
      { title: "Sesiones de inicio reconstruidas", body: "Quién inició sesión, cómo, desde dónde, con qué privilegios y qué hizo — de 4624 a 4634, una fila por sesión." },
      { title: "Notas e informe Markdown", body: "Marca y anota eventos, exporta un informe limpio o comparte una vista filtrada con un enlace." },
      { title: "Offline y de código abierto", body: "Funciona aislado en Docker, Elastic License 2.0, parser en Rust auditable en GitHub." },
    ],
    statusReading: "Leyendo {name}…",
    statusParsing: "Analizando el registro de eventos…",
    eventsLabel: "eventos",
    filterPlaceholder: "Buscar en todos los campos… p. ej. mimikatz, EventID:4624 LogonType:10 -IpAddress:127.0.0.1",
    clearFilter: "Limpiar",
    noMatches: "Ningún evento coincide con el filtro.",
    topIds: "IDs frecuentes",
    exportCsv: "Exportar CSV",
    exportJson: "Exportar JSON",
    exportTxt: "Exportar TXT",
    includeXml: "Columna XML sin procesar",
    exporting: "Exportando…",
    clearTime: "Limpiar rango horario",
    clearAll: "Borrar todo",
    clearFilters: "Borrar filtros",
    removeFile: "Quitar archivo",
    enterFullscreen: "Pantalla completa",
    exitFullscreen: "Salir de pantalla completa",
    whatIsHeading: "¿Qué es un archivo EVTX?",
    whatIsBody:
      "Un archivo .evtx es un registro de eventos de Windows — el formato binario que Windows usa desde Vista para guardar eventos de seguridad, sistema y aplicaciones. Están en C:\\Windows\\System32\\winevt\\Logs (Security.evtx, System.evtx, Application.evtx…) y no son texto plano, así que el Bloc de notas no puede leerlos. Suelta uno arriba para verlo.",
    whatIsMore: "Guía completa del formato EVTX",
  },
  viewer: {
    fields: "Campos",
    hideFields: "Ocultar campos",
    top: "Frecuentes",
    rare: "Raros",
    filterValues: "Filtrar valores…",
    showMore: "Mostrar más",
    showLess: "Mostrar menos",
    addField: "Añadir un campo…",
    include: "Filtrar por este valor",
    exclude: "Excluir este valor",
    remove: "Quitar",
    pivots: "Pivotar",
    pivotTime: "Alrededor de este evento",
    pivotLogon: "Misma sesión de inicio",
    pivotProcess: "Mismo proceso",
    syntaxHelp: "Sintaxis de búsqueda",
    helpFree: "Busca en todos los campos, incluido EventData",
    helpField: "Campo igual a valor",
    helpWildcard: "Comodín *",
    helpNot: "Excluir con un - delante",
    helpOr: "Cualquiera de los términos",
    helpCompare: "Comparación numérica",
    helpPivot: "Todos los eventos de una sesión de inicio",
    helpProcess: "Imagen del proceso o del padre (4688 o Sysmon)",
    noValues: "Sin valores",
    suggestions: "Sugerencias",
    description: "Descripción",
    copy: "Copiar",
    copied: "Copiado",
    copyJson: "Copiar como JSON",
    copyXml: "Copiar XML",
    timeZoneToggle: "Mostrar la hora en UTC o en tu zona horaria",
    hunts: "Cacerías",
    huntsHint: "Búsquedas en un clic de actividad habitual de atacantes. Recuentos sobre los archivos cargados.",
    catCredential: "Acceso a credenciales",
    catLateral: "Movimiento lateral",
    catPersistence: "Persistencia",
    catExecution: "Ejecución",
    catEvasion: "Evasión de defensas",
    catInitial: "Acceso inicial",
    catDiscovery: "Descubrimiento",
    catImpact: "Impacto",
    catC2: "Mando y control / exfiltración",
    huntsFilter: "Filtrar cacerías…",
    hitsOnly: "Solo cacerías con resultados",
    eventsTab: "Eventos",
    sessionsTab: "Sesiones de inicio",
    sessionsHint: "Una fila por inicio de sesión, tokens UAC fusionados. Haz clic en una sesión para ver todos sus eventos.",
    sessionStart: "Inicio",
    sessionEnd: "Cierre",
    sessionDuration: "Duración",
    sessionUser: "Cuenta",
    sessionType: "Tipo de inicio",
    sessionSource: "Origen",
    sessionAdmin: "Admin",
    sessionEvents: "Eventos",
    sessionActivity: "Actividad",
    sessionOpen: "aún abierta",
    sessionUnknownStart: "antes del inicio del registro",
    showSystemSessions: "Mostrar sesiones de sistema y de servicio",
    noSessions: "No hay sesiones de inicio en los registros cargados — las sesiones se construyen a partir de eventos Security 4624.",
    filesLabel: "archivos",
    fileLabel: "archivo",
    showFiles: "Mostrar archivos",
    hideFiles: "Ocultar archivos",
    showControls: "Mostrar hallazgos y cronología",
    hideControls: "Ocultar hallazgos y cronología",
    rangeTitle: "Rango de tiempo",
    rangeFrom: "Desde",
    rangeTo: "Hasta",
    rangeInvalid: "El inicio no puede ser posterior al fin",
    rangePreset: "Preajuste",
    presetAll: "Todo",
    presetFirstHour: "Primera hora",
    presetLastHour: "Última hora",
    presetLast24h: "Últimas 24 h de los datos",
    rangeAround: "Alrededor",
    rangeAroundHint: "Haz clic en una marca de tiempo de la tabla para centrar el rango en ella",
    aroundTimeTitle: "Mostrar {window} alrededor de esta hora",
    rangeField: "Campo de tiempo",
    rangeFieldPrimary: "Hora del evento (TimeCreated)",
    rangeFieldAny: "Cualquier campo de tiempo",
    rangeFieldHint: "Los registros sin valor en este campo se ocultan mientras haya un rango activo.",
    rangeCount: "{n} de {total} registros",
    rangeStrip: "Eventos en el tiempo: arrastra para seleccionar un rango; las flechas mueven los controles",
    rangeStart: "Inicio del rango",
    rangeEnd: "Fin del rango",
    rangeBarEvents: "{n} eventos",
    win5m: "±5 min",
    win1h: "±1 h",
    win24h: "±24 h",
    pinColumn: "Fijar columna",
    unpinColumn: "Desfijar columna",
    resizeColumn: "Arrastra para redimensionar · doble clic para ajustar al contenido",
    resetColumns: "Restablecer columnas",
    saveSession: "Guardar sesión",
    sessionSaved: "Sesión guardada",
    savingSession: "Guardando…",
    savedSessionsTitle: "Sesiones guardadas en este dispositivo",
    savedSessionsHint: "Guardadas solo en este navegador (IndexedDB) — no se sube nada. Continúa donde lo dejaste o elimínalas.",
    resumeSession: "Reanudar",
    deleteSession: "Eliminar",
    confirmDeleteSession: "¿Eliminar esta sesión guardada? Solo se borra la copia almacenada en este navegador; tus archivos en disco no se ven afectados.",
    cancel: "Cancelar",
    sessionName: "Nombre de la sesión",
    saveSessionTitle: "Guardar esta sesión",
    saveSessionDescription: "Se guarda solo en este navegador — no se sube nada. Una vez guardada, tus cambios se guardan automáticamente.",
    renameSessionTitle: "Renombrar sesión",
    renameSession: "Renombrar",
    saveAction: "Guardar",
    deleteSessionTitle: "¿Eliminar la sesión guardada?",
    restoringSession: "Restaurando la sesión…",
    storageFull: "No hay suficiente almacenamiento en el navegador para guardar estos archivos.",
    autoSaved: "Guardado automático",
    autoSaveHint: "Guardada en este navegador — los cambios se guardan automáticamente. Haz clic para guardar ahora.",
    note: "Nota del analista",
    notePlaceholder: "Añadir una nota para el informe…",
    report: "Informe (.md)",
    reportTitle: "Informe de investigación EVTX",
    reportGenerated: "Generado",
    copyLink: "Copiar enlace de esta búsqueda",
    linkCopied: "Enlace copiado",
  },
  collect: {
    heading: "Cómo obtener tus archivos .evtx",
    intro:
      "¿Nunca has sacado registros de eventos de un equipo Windows? Elige el primer método que te sirva: es cuestión de un minuto.",
    steps: [
      "Recopila los archivos .evtx",
      "Suéltalos aquí (puedes soltar varios a la vez)",
      "Todo se queda en tu navegador",
    ],
    tabsLabel: "Métodos de recopilación",
    tabQuick: "Lo más rápido",
    tabTriage: "Herramientas de triaje",
    tabImage: "Desde una imagen de disco",
    tabLocation: "Dónde están",
    recommended: "Recomendado",
    quickPrereq:
      "Ejecuta como administrador en el equipo Windows (clic derecho en PowerShell o en el Símbolo del sistema → Ejecutar como administrador). Leer el registro de Seguridad requiere permisos de administrador.",
    quickPsLabel: "Exporta los registros clave de una vez",
    quickPsNote:
      "Guarda los registros Security, System, Application, PowerShell y Sysmon en `C:\\triage\\`. Si un registro no existe en el equipo (p. ej., Sysmon no está instalado), solo muestra un error: ignóralo. Después suelta aquí los archivos de `C:\\triage\\`.",
    quickCmdLabel: "Solo el registro de Seguridad",
    quickGuiLabel: "¿Sin línea de comandos? Usa el Visor de eventos",
    quickGui:
      "Ejecuta `eventvwr.msc` → Registros de Windows → clic derecho en Seguridad (o cualquier registro) → «Guardar todos los eventos como…» (Save All Events As…) → deja el tipo «Archivos de eventos (*.evtx)» → Guardar.",
    triagePrereq:
      "Ejecuta como administrador. KAPE y Velociraptor son descargas gratuitas aparte, desde sus páginas oficiales. También recogen los archivos archivados `Archive-*.evtx` que una exportación omite.",
    kapeLabel: "KAPE — target EventLogs",
    kapeNote:
      "Copia todos los .evtx de `winevt\\Logs` dentro de `C:\\triage\\`, conservando la estructura de carpetas original. Abre esa carpeta `Logs`, selecciona todos los .evtx y suéltalos aquí.",
    veloLabel: "Velociraptor — recolector offline",
    veloGui:
      "En la interfaz de Velociraptor: Server Artifacts → Build offline collector → selecciona `Windows.Triage.Targets` (del proyecto Velociraptor Triage) → marca el target `EventLogs` → genéralo y ejecuta el recolector en el equipo como administrador. Genera un ZIP de la recopilación. Descomprime primero: los .evtx están bajo la carpeta `winevt/Logs` del archivo.",
    veloCmdLabel: "Versiones antiguas de Velociraptor — línea de comandos",
    veloNote:
      "Solo para versiones que aún incluyen `Windows.KapeFiles.Targets`, el nombre anterior del artefacto de triaje. Recoge su target `EventLogs` en `C:\\triage\\evtx.zip`; pon el nombre de tu binario de Velociraptor. Descomprime primero: los .evtx están bajo la carpeta `winevt/Logs` del archivo.",
    imageIntro:
      "¿Ya tienes una imagen E01/raw o una copia del disco? Extrae los archivos de `\\Windows\\System32\\winevt\\Logs\\` de la partición de Windows: no hacen falta permisos de administrador ni el equipo encendido.",
    ftkLabel: "FTK Imager",
    ftkSteps:
      "File → Add Evidence Item → Image File → navega hasta `[root]\\Windows\\System32\\winevt\\Logs` → selecciona los .evtx → clic derecho → Export Files.",
    mountLabel: "Imagen montada (Linux / macOS)",
    mountNote:
      "Supone que la partición de Windows está montada en solo lectura en `/mnt/win` (p. ej., `ewfmount` + `mount -o ro`, o Arsenal Image Mounter en Windows): ajusta la ruta a tu punto de montaje.",
    locationIntro:
      "Cada canal del registro de eventos es un archivo .evtx independiente, todos en la misma carpeta (Windows Vista / Server 2008 y posteriores):",
    locationFiles:
      "Archivos principales: `Security.evtx`, `System.evtx`, `Application.evtx`; la `/` de un nombre de canal pasa a ser `%4`, p. ej. `Microsoft-Windows-Sysmon%4Operational.evtx`. Cada archivo es autónomo, sin archivos complementarios. Suelta varios y se combinan en una sola línea de tiempo.",
    locationArchive:
      "Los registros rotados se guardan al lado como `Archive-Security-<marca de tiempo>.evtx` si la copia automática está activada: suéltalos también.",
    locationRedirect: "¿Registro movido? Comprueba su ruta real (logFileName)",
    allPaths: "Todas las rutas por canal",
    gotchasHeading: "Errores habituales",
    gotchas: [
      "Una copia normal de un registro activo falla porque Windows lo mantiene abierto: usa uno de los métodos anteriores, no el Explorador ni `copy`.",
      "Los registros son circulares: al llenarse, se sobrescriben los eventos más antiguos (el tamaño por defecto suele ser de solo 20 MB). Recopila pronto y coge también los `Archive-*.evtx`: `wevtutil epl` solo exporta el registro activo.",
      "Suelta archivos .evtx, no un .zip ni una carpeta: descomprime primero y selecciona todos los .evtx. Las horas se muestran en UTC por defecto (cambia a hora local en el visor).",
    ],
    copy: "Copiar",
    copyCommand: "Copiar comando",
    copied: "Copiado",
    openGuide: "Cómo recopilar",
  },
  fileLocation: {
    heading: "Dónde encontrar los archivos .evtx",
    intro:
      "En el equipo de origen, cada canal del registro de eventos es un archivo .evtx independiente, todos en la misma carpeta. Las rutas asumen la carpeta de Windows predeterminada, C:\\Windows (%SystemRoot%).",
    allChannels: "Carpeta de registros — todos los canales",
    vistaPlus: "Windows Vista / Server 2008+",
    archived:
      "Registros archivados (Archive-<canal>-<marca de tiempo>.evtx, si el archivado automático está activo)",
    legacy:
      "Formato heredado .evt (también AppEvent.Evt, SysEvent.Evt) — no compatible aquí",
    howToHeading: "Cómo obtenerlo",
    howTo: [
      "El servicio EventLog mantiene abiertos los registros activos, así que una copia normal falla. Desde una consola de administrador, `wevtutil epl Security C:\\triage\\Security.evtx` exporta una copia limpia (solo el registro activo — omite los archivos Archive-*).",
      "Para copiar la carpeta completa tal cual: KAPE (`--target EventLogs`), FTK Imager o RawCopy — o léala sin conexión desde una imagen E01 montada o una instantánea de volumen (VSS).",
      "Cada .evtx es autónomo, no necesita archivos complementarios. Un canal puede estar redirigido: confirme la ruta real con `wevtutil gl <canal>` (logFileName).",
    ],
    readMore: "Guía de recolección: 4 métodos comparados",
    copy: "Copiar ruta",
    copied: "Copiado",
  },
  table: {
    record: "Reg. #",
    time: "Hora (UTC)",
    level: "Nivel",
    eventId: "ID de evento",
    name: "Nombre",
    summary: "Resumen",
    provider: "Proveedor",
    channel: "Canal",
    computer: "Equipo",
    source: "Origen",
    viewDetails: "Detalles",
    closeDetails: "Cerrar",
    eventData: "Datos del evento",
    noEventData: "Este registro no tiene campos EventData.",
    showRawXml: "Mostrar XML en bruto",
    hideRawXml: "Ocultar XML en bruto",
    prev: "ant.",
    next: "sig.",
  },
  levels: {
    critical: "Crítico",
    error: "Error",
    warning: "Advertencia",
    info: "Información",
    verbose: "Detallado",
    unknown: "—",
  },
  filter: {
    advanced: "Filtros avanzados",
    addCondition: "Añadir condición",
    addGroup: "Añadir grupo",
    removeCondition: "Eliminar condición",
    removeGroup: "Eliminar grupo",
    and: "Y",
    or: "O",
    reset: "Restablecer filtros",
    matchCount: "{count} eventos coincidentes",
    eventDataKey: "Nombre del campo",
    eventDataKeyPlaceholder: "p. ej. TargetUserName",
    valuePlaceholder: "valor",
    fields: {
      level: "Nivel",
      category: "Tipo de evento",
      eventId: "ID de evento",
      provider: "Proveedor",
      channel: "Canal",
      computer: "Equipo",
      file: "Archivo de origen",
      eventName: "Nombre del evento",
      timestamp: "Fecha y hora",
      eventData: "Campo EventData",
    },
    ops: {
      contains: "contiene",
      notContains: "no contiene",
      equals: "es igual a",
      notEquals: "es distinto de",
      startsWith: "empieza por",
      regex: "coincide con (regex)",
      exists: "está presente",
      empty: "está vacío",
      eq: "=",
      neq: "≠",
      lt: "<",
      lte: "≤",
      gt: ">",
      gte: "≥",
      in: "es alguno de",
      notIn: "no es ninguno de",
      before: "antes de",
      after: "después de",
      between: "entre",
    },
    categories: {
      security: "Seguridad",
      system: "Sistema",
      sysmon: "Sysmon",
      powershell: "PowerShell",
      defender: "Defender",
      appLocker: "AppLocker",
      taskScheduler: "Programador de tareas",
      rdpLocal: "RDP (sesión local)",
      rdpRemote: "RDP (conexión remota)",
      rdpCore: "RDP (núcleo)",
      wmiActivity: "Actividad WMI",
      firewall: "Firewall",
      bits: "BITS",
      smbServer: "Servidor SMB",
      smbClient: "Cliente SMB",
      wlan: "WLAN",
      other: "Otro",
    },
  },
  faq: {
    heading: "Preguntas sobre el registro de eventos",
    items: [
      {
        q: "¿Qué es un archivo EVTX?",
        a: "EVTX es el formato binario del registro de eventos de Windows introducido con Windows Vista. Cada .evtx es una secuencia de bloques de 64 KB; cada bloque contiene una tabla de plantillas XML y un flujo de registros que las referencian. El análisis reconstruye el XML completo de cada evento.",
      },
      {
        q: "¿Dónde se encuentran los .evtx en Windows?",
        a: "Los registros activos están en C:\\Windows\\System32\\winevt\\Logs. Los tres principales en forense son Security.evtx (inicios de sesión, privilegios), System.evtx (controladores, servicios) y Application.evtx (errores de aplicación). Los canales Sysmon y PowerShell suelen ser los más valiosos en respuesta a incidentes.",
      },
      {
        q: "¿Esta herramienta sube mi .evtx a algún sitio?",
        a: "No. El análisis se hace en un Web Worker con un parser EVTX en Rust compilado a WebAssembly. El archivo se lee en memoria del navegador y nunca se transmite. Desconecta la red si quieres comprobarlo.",
      },
      {
        q: "¿Qué significa la columna Nivel?",
        a: "Los niveles EVTX son numéricos: 1 Crítico, 2 Error, 3 Advertencia, 4 Información, 5 Detallado. Microsoft asigna algunos IDs habituales (p. ej. Security 4625 = autenticación fallida a nivel Información) — la severidad por sí sola no basta para priorizar.",
      },
      {
        q: "¿Puede manejar archivos .evtx muy grandes?",
        a: "El análisis corre en un Web Worker. La memoria escala con el tamaño; varios cientos de MB son cómodos en navegadores modernos. Para colecciones mayores, exporta con evtx_dump y recarga por tramos.",
      },
    ],
  },
  footer: {
    blog: "Blog",
    builtWith:
      "Construido con WebAssembly y el crate de Rust omerbenamram/evtx. 100 % cliente — los archivos nunca salen del navegador.",
  },
  notFound: {
    title: "404 — página no encontrada",
    heading: "Página no encontrada",
    description:
      "Esta URL no existe en el sitio. Puede que se haya movido, o que sigas un enlace antiguo.",
    backHome: "← Volver al inicio",
  },
  blog: {
    indexTitle: "Notas sobre el registro de eventos",
    indexIntro:
      "Notas breves sobre el formato binario del registro de eventos de Windows, IDs útiles en forense y flujos de triage.",
    readMore: "Leer más",
    backToBlog: "← Volver al blog",
    publishedOn: "Publicado",
    updatedOn: "Actualizado",
    readingTime: "{n} min de lectura",
    prevPost: "← Anterior",
    nextPost: "Siguiente →",
    relatedHeading: "Artículos relacionados",
    resourcesHeading: "Recursos externos",
    byLine: "Por",
  },
  eventIds: {
    title: "Referencia de Event ID de Windows",
    intro:
      "Índice curado de los Event ID de Windows que importan en un caso forense — agrupados por canal, con los campos EventData más útiles. Haz clic en un ID cubierto para la guía detallada; los demás enlazan a Microsoft Learn.",
    description:
      "Índice de referencia de Event ID de Windows útiles en DFIR: Security 4624/4625/1102, System 7045/7036, Sysmon 1/3/7/11, PowerShell 4104, TaskScheduler, Kerberos — con enlaces a guías detalladas.",
    columnId: "Event ID",
    columnName: "Nombre",
    columnNotes: "Notas",
  },
  glossary: {
    title: "Glosario del registro de eventos de Windows",
    intro:
      "Los términos que aparecen en los registros .evtx y los informes DFIR, explicados en una o dos frases.",
    description:
      "Definiciones claras de los términos del registro de eventos de Windows: LogonType, BinXML, canal, provider, chunk, template, SID, EventData, RecordID, etc.",
  },
  tools: {
    title: "Herramientas EVTX comparadas: KAPE, FTK Imager, wevtutil, evtx_dump",
    intro:
      "Comparación lado a lado de las herramientas que un analista usa con el log de eventos de Windows — para qué sirve cada una, qué cuesta y dónde falla.",
    description:
      "Compara KAPE, FTK Imager, wevtutil, evtx_dump, python-evtx, RawCopy y EVTX parser — por plataforma, caso de uso, licencia y limitaciones.",
    columnTool: "Herramienta",
    columnPlatform: "Plataforma",
    columnUseCase: "Caso de uso principal",
    columnLicense: "Licencia",
  },
  breadcrumb: {
    home: "Inicio",
    label: "Ruta de migas",
  },
  eventId: {
    title: "Event ID {id}: {name} ({channel})",
    intro:
      "Lo que este Event ID realmente registra en disco, los campos EventData a leer primero y su lugar en un flujo de triage DFIR.",
    description:
      "Windows Event ID {id} ({name}) en el canal {channel}: significado, campos EventData, técnicas ofensivas comunes y Event IDs relacionados.",
    channelLabel: "Canal",
    providerLabel: "Proveedor",
    notesLabel: "Notas de triage",
    inDepthHeading: "Guía detallada",
    inDepthCta: "Leer el análisis completo",
    microsoftLearnHeading: "Microsoft Learn",
    microsoftLearnCta: "Abrir la referencia oficial",
    relatedHeading: "Event IDs relacionados",
    notCoveredYet:
      "Este Event ID está en el índice pero aún no tiene un análisis detallado. Microsoft Learn cubre los campos a nivel de protocolo.",
    notFoundTitle: "Event ID desconocido",
    notFoundDescription:
      "Este Event ID aún no figura en el índice de referencia.",
  },
  tags: {
    indexTitle: "Temas — todas las etiquetas del blog",
    indexIntro:
      "Todos los temas tratados en el blog, con el número de artículos por etiqueta. Sirve como segundo eje de navegación junto al índice de Event ID.",
    indexDescription:
      "Explora los temas del blog EVTX parser: auditoría Security, Sysmon, PowerShell, Kerberos, servicios, internos del formato EVTX y colección forense.",
    tagTitleTemplate: "Artículos con la etiqueta «{tag}»",
    tagIntroTemplate:
      "Todos los artículos del blog con la etiqueta «{tag}», más recientes primero.",
    tagDescriptionTemplate:
      "Artículos de forense del log de eventos de Windows con la etiqueta «{tag}» — notas DFIR, técnicas ofensivas e internos del parser.",
    postsCount: "{n} artículos",
    tagsOnPost: "Etiquetas",
    labels: {
      security: "Auditoría Security",
      logon: "Inicio de sesión",
      process: "Proceso",
      account: "Cuenta",
      privileges: "Privilegios",
      "object-access": "Acceso a objetos",
      kerberos: "Kerberos",
      "anti-forensics": "Anti-forense",
      attack: "Técnicas ofensivas",
      sysmon: "Sysmon",
      powershell: "PowerShell",
      system: "Canal System",
      service: "Servicio",
      persistence: "Persistencia",
      format: "Formato EVTX",
      fundamentals: "Fundamentos",
      collection: "Colección",
      tooling: "Herramientas",
      navigation: "Navegación",
    },
  },
  toc: {
    heading: "En esta página",
  },
};
