import type { Dict } from "./types";

export const fr: Dict = {
  meta: {
    title: "Visionneuse EVTX en ligne — ouvrir un fichier .evtx sans envoi",
    description:
      "Un fichier .evtx est un journal d'événements Windows. Ouvrez-le gratuitement dans le navigateur — sans envoi ni installation — filtrez et exportez en CSV, TXT, JSON ou XML.",
    siteName: "EVTX parser",
  },
  home: {
    heading: "EVTX parser",
    headline: "EVTX parser — visualiseur de journaux Windows dans le navigateur",
    intro:
      "Déposez un journal d'événements Windows .evtx. L'analyse s'exécute entièrement dans votre navigateur via WebAssembly — rien n'est téléversé.",
    featuredHeading: "Guides en vedette",
    dropArea: "Déposez un .evtx ici ou cliquez pour choisir",
    privacyNote: "Les fichiers restent sur votre appareil. Analyse 100 % côté client.",
    heroTag: "Open source · 100 % dans votre navigateur",
    heroCtaOpen: "Ouvrir un fichier .evtx",
    heroCtaGithub: "Voir sur GitHub",
    footerTagline: "L'analyse forensique des journaux Windows, entièrement dans votre navigateur.",
    statHunts: "règles de chasse intégrées",
    statUploaded: "octet téléversé",
    statEngine: "analyseur compilé en WebAssembly",
    statLocales: "langues",
    worksWith: "Lit tous les canaux que vous collectez",
    featuresEyebrow: "Conçu pour la réponse à incident",
    featuresHeading: "Du .evtx brut aux constats en quelques minutes",
    featuresIntro: "Tout ce dont un analyste DFIR a besoin, sans installer l'Observateur d'événements, Python ou un SIEM.",
    ctaHeading: "Votre prochaine investigation commence par un glisser-déposer.",
    ctaBody: "Gratuit, open source et privé par conception. Sans compte, sans envoi, sans installation.",
    features: [
      { title: "Des chasses dès l'ouverture", body: "{n} détections — Kerberoasting, effacement des journaux, cradles PowerShell, nouveaux services, force brute — lancées dès le chargement." },
      { title: "Un langage de requête d'analyste", body: "Champ:valeur, jokers, guillemets et négation sur tous les champs EventData, avec facettes instantanées et tri des valeurs rares." },
      { title: "Pivots en un clic", body: "Passez de n'importe quel événement au même Logon ID, au même GUID de processus, au parent ou à une fenêtre de ±5 minutes." },
      { title: "Sessions de connexion reconstruites", body: "Qui s'est connecté, comment, d'où, avec quels privilèges et ce qu'il a fait — de 4624 à 4634, une ligne par session." },
      { title: "Notes et rapport Markdown", body: "Marquez et annotez des événements, exportez un rapport propre ou partagez une vue filtrée par lien." },
      { title: "Hors ligne et open source", body: "Fonctionne isolé dans Docker, licence Elastic 2.0, analyseur Rust auditable sur GitHub." },
    ],
    statusReading: "Lecture de {name}…",
    statusParsing: "Analyse du journal d'événements…",
    eventsLabel: "événements",
    filterPlaceholder: "Rechercher dans tous les champs… ex. mimikatz, EventID:4624 LogonType:10 -IpAddress:127.0.0.1",
    clearFilter: "Effacer",
    noMatches: "Aucun événement ne correspond au filtre.",
    topIds: "IDs fréquents",
    exportCsv: "Exporter CSV",
    exportJson: "Exporter JSON",
    exportTxt: "Exporter TXT",
    includeXml: "Colonne XML brut",
    exporting: "Export en cours…",
    clearTime: "Effacer la plage horaire",
    clearAll: "Tout effacer",
    clearFilters: "Effacer les filtres",
    removeFile: "Retirer le fichier",
    enterFullscreen: "Plein écran",
    exitFullscreen: "Quitter le plein écran",
    whatIsHeading: "Qu'est-ce qu'un fichier EVTX ?",
    whatIsBody:
      "Un fichier .evtx est un journal d'événements Windows — le format binaire utilisé depuis Vista pour enregistrer les événements de sécurité, système et application. Ils se trouvent dans C:\\Windows\\System32\\winevt\\Logs (Security.evtx, System.evtx, Application.evtx…) et ne sont pas du texte brut : le Bloc-notes ne peut pas les lire. Déposez-en un ci-dessus pour l'afficher.",
    whatIsMore: "Guide complet du format EVTX",
  },
  viewer: {
    fields: "Champs",
    hideFields: "Masquer les champs",
    top: "Fréquents",
    rare: "Rares",
    filterValues: "Filtrer les valeurs…",
    showMore: "Afficher plus",
    showLess: "Afficher moins",
    addField: "Ajouter un champ…",
    include: "Filtrer sur cette valeur",
    exclude: "Exclure cette valeur",
    remove: "Retirer",
    pivots: "Pivot",
    pivotTime: "±5 min autour de cet événement",
    pivotLogon: "Même session de connexion",
    pivotProcess: "Même processus",
    syntaxHelp: "Syntaxe de recherche",
    helpFree: "Recherche dans tous les champs, EventData compris",
    helpField: "Champ égal à la valeur",
    helpWildcard: "Joker *",
    helpNot: "Exclure avec un - devant",
    helpOr: "L'un ou l'autre",
    helpCompare: "Comparaison numérique",
    helpPivot: "Tous les événements d'une session de connexion",
    helpProcess: "Image du processus ou du parent (4688 ou Sysmon)",
    noValues: "Aucune valeur",
    suggestions: "Suggestions",
    description: "Description",
    copy: "Copier",
    copied: "Copié",
    copyJson: "Copier en JSON",
    copyXml: "Copier le XML",
    timeZoneToggle: "Afficher l'heure en UTC ou dans votre fuseau horaire",
    hunts: "Chasses",
    huntsHint: "Recherches en un clic des activités d'attaquant courantes. Comptes sur les fichiers chargés.",
    catCredential: "Accès aux identifiants",
    catLateral: "Mouvement latéral",
    catPersistence: "Persistance",
    catExecution: "Exécution",
    catEvasion: "Contournement des défenses",
    catInitial: "Accès initial",
    catDiscovery: "Découverte",
    catImpact: "Impact",
    catC2: "Commande et contrôle / exfiltration",
    huntsFilter: "Filtrer les chasses…",
    hitsOnly: "Seulement les chasses avec résultats",
    eventsTab: "Événements",
    sessionsTab: "Sessions de connexion",
    sessionsHint: "Une ligne par connexion, jetons UAC fusionnés. Cliquez sur une session pour voir tous ses événements.",
    sessionStart: "Connexion",
    sessionEnd: "Déconnexion",
    sessionDuration: "Durée",
    sessionUser: "Compte",
    sessionType: "Type de connexion",
    sessionSource: "Source",
    sessionAdmin: "Admin",
    sessionEvents: "Événements",
    sessionActivity: "Activité",
    sessionOpen: "toujours ouverte",
    sessionUnknownStart: "avant le début du journal",
    showSystemSessions: "Afficher les sessions système et de service",
    noSessions: "Aucune session de connexion dans les journaux chargés — les sessions sont construites à partir des événements Security 4624.",
    filesLabel: "fichiers",
    fileLabel: "fichier",
    showFiles: "Afficher les fichiers",
    hideFiles: "Masquer les fichiers",
    showControls: "Afficher constats et chronologie",
    hideControls: "Masquer constats et chronologie",
    rangeTitle: "Plage horaire",
    rangeFrom: "Du",
    rangeTo: "Au",
    rangeApply: "Appliquer",
    rangeInvalid: "Le début doit précéder la fin",
    pinColumn: "Épingler la colonne",
    unpinColumn: "Désépingler la colonne",
    resizeColumn: "Glisser pour redimensionner · double-clic pour ajuster au contenu",
    resetColumns: "Réinitialiser les colonnes",
    saveSession: "Enregistrer la session",
    sessionSaved: "Session enregistrée",
    savingSession: "Enregistrement…",
    savedSessionsTitle: "Sessions enregistrées sur cet appareil",
    savedSessionsHint: "Stockées uniquement dans ce navigateur (IndexedDB) — rien n'est envoyé. Reprenez là où vous en étiez, ou supprimez-les.",
    resumeSession: "Reprendre",
    deleteSession: "Supprimer",
    confirmDeleteSession: "Supprimer cette session enregistrée ? Seule la copie stockée dans ce navigateur est supprimée — vos fichiers sur le disque ne sont pas touchés.",
    cancel: "Annuler",
    sessionName: "Nom de la session",
    saveSessionTitle: "Enregistrer cette session",
    saveSessionDescription: "Stockée uniquement dans ce navigateur — rien n'est envoyé. Une fois enregistrée, vos modifications sont sauvegardées automatiquement.",
    renameSessionTitle: "Renommer la session",
    renameSession: "Renommer",
    saveAction: "Enregistrer",
    deleteSessionTitle: "Supprimer la session enregistrée ?",
    restoringSession: "Restauration de la session…",
    storageFull: "Pas assez d'espace de stockage navigateur pour enregistrer ces fichiers.",
    autoSaved: "Enregistrement auto",
    autoSaveHint: "Enregistrée dans ce navigateur — les modifications sont enregistrées automatiquement. Cliquez pour enregistrer maintenant.",
    note: "Note d'analyse",
    notePlaceholder: "Ajouter une note pour le rapport…",
    report: "Rapport (.md)",
    reportTitle: "Rapport d'investigation EVTX",
    reportGenerated: "Généré le",
    copyLink: "Copier le lien de cette recherche",
    linkCopied: "Lien copié",
  },
  fileLocation: {
    heading: "Où trouver les fichiers .evtx",
    intro:
      "Sur la machine source, chaque canal du journal d'événements est un fichier .evtx distinct, tous dans le même dossier. Les chemins supposent le dossier Windows par défaut, C:\\Windows (%SystemRoot%).",
    allChannels: "Dossier des journaux — tous les canaux",
    vistaPlus: "Windows Vista / Server 2008+",
    archived:
      "Journaux archivés (Archive-<canal>-<horodatage>.evtx, si l'archivage auto est activé)",
    legacy:
      "Ancien format .evt (aussi AppEvent.Evt, SysEvent.Evt) — non pris en charge ici",
    howToHeading: "Comment le récupérer",
    howTo: [
      "Le service EventLog garde les journaux actifs ouverts : une simple copie échoue. Dans un shell administrateur, `wevtutil epl Security C:\\triage\\Security.evtx` exporte une copie propre (journal actif uniquement — les fichiers Archive-* sont ignorés).",
      "Pour récupérer le dossier entier tel quel : KAPE (`--target EventLogs`), FTK Imager ou RawCopy — ou lecture hors ligne depuis une image E01 montée ou un cliché instantané (VSS).",
      "Chaque .evtx est autonome, aucun fichier compagnon n'est requis. Un canal peut être redirigé : vérifiez le chemin réel avec `wevtutil gl <canal>` (logFileName).",
    ],
    readMore: "Guide de collecte : 4 méthodes comparées",
    copy: "Copier le chemin",
    copied: "Copié",
  },
  table: {
    record: "Enr. #",
    time: "Heure (UTC)",
    level: "Niveau",
    eventId: "ID d'événement",
    name: "Nom",
    summary: "Résumé",
    provider: "Fournisseur",
    channel: "Canal",
    computer: "Ordinateur",
    source: "Source",
    viewDetails: "Détails",
    closeDetails: "Fermer",
    eventData: "Données d'événement",
    noEventData: "Aucun champ EventData pour cet enregistrement.",
    showRawXml: "Afficher le XML brut",
    hideRawXml: "Masquer le XML brut",
    prev: "préc.",
    next: "suiv.",
  },
  levels: {
    critical: "Critique",
    error: "Erreur",
    warning: "Avertissement",
    info: "Information",
    verbose: "Détaillé",
    unknown: "—",
  },
  filter: {
    advanced: "Filtres avancés",
    addCondition: "Ajouter une condition",
    addGroup: "Ajouter un groupe",
    removeCondition: "Supprimer la condition",
    removeGroup: "Supprimer le groupe",
    and: "ET",
    or: "OU",
    reset: "Réinitialiser les filtres",
    matchCount: "{count} événements correspondants",
    eventDataKey: "Nom du champ",
    eventDataKeyPlaceholder: "ex. TargetUserName",
    valuePlaceholder: "valeur",
    fields: {
      level: "Niveau",
      category: "Type d'événement",
      eventId: "ID d'événement",
      provider: "Fournisseur",
      channel: "Canal",
      computer: "Ordinateur",
      file: "Fichier source",
      eventName: "Nom de l'événement",
      timestamp: "Horodatage",
      eventData: "Champ EventData",
    },
    ops: {
      contains: "contient",
      notContains: "ne contient pas",
      equals: "égal à",
      notEquals: "différent de",
      startsWith: "commence par",
      regex: "correspond à (regex)",
      exists: "est présent",
      empty: "est vide",
      eq: "=",
      neq: "≠",
      lt: "<",
      lte: "≤",
      gt: ">",
      gte: "≥",
      in: "parmi",
      notIn: "aucun de",
      before: "avant",
      after: "après",
      between: "entre",
    },
    categories: {
      security: "Sécurité",
      system: "Système",
      sysmon: "Sysmon",
      powershell: "PowerShell",
      defender: "Defender",
      appLocker: "AppLocker",
      taskScheduler: "Planificateur de tâches",
      rdpLocal: "RDP (session locale)",
      rdpRemote: "RDP (connexion distante)",
      rdpCore: "RDP (cœur)",
      wmiActivity: "Activité WMI",
      firewall: "Pare-feu",
      bits: "BITS",
      smbServer: "Serveur SMB",
      smbClient: "Client SMB",
      wlan: "WLAN",
      other: "Autre",
    },
  },
  faq: {
    heading: "FAQ journaux d'événements",
    items: [
      {
        q: "Qu'est-ce qu'un fichier EVTX ?",
        a: "EVTX est le format binaire du journal d'événements Windows introduit avec Windows Vista. Chaque fichier .evtx est une suite de blocs de 64 Ko ; chaque bloc contient une table de modèles XML suivie d'un flux d'enregistrements qui y font référence. L'analyse reconstitue le XML complet de chaque événement.",
      },
      {
        q: "Où se trouvent les fichiers .evtx sous Windows ?",
        a: "Les journaux actifs se trouvent sous C:\\Windows\\System32\\winevt\\Logs. Les trois principaux en forensique sont Security.evtx (connexions, privilèges), System.evtx (pilotes, services) et Application.evtx (erreurs applicatives). Les canaux Sysmon et PowerShell sont généralement les plus précieux en réponse à incident.",
      },
      {
        q: "Cet outil envoie-t-il mes .evtx quelque part ?",
        a: "Non. L'analyse s'effectue dans un Web Worker via un parseur EVTX en Rust compilé en WebAssembly. Le fichier est chargé en mémoire dans le navigateur et n'est jamais transmis. Coupez le réseau si vous souhaitez le vérifier.",
      },
      {
        q: "Que signifie la colonne Niveau ?",
        a: "Les niveaux EVTX sont numériques : 1 Critique, 2 Erreur, 3 Avertissement, 4 Information, 5 Détaillé. Microsoft place certains ID classiques (ex. Security 4625 = échec d'authentification au niveau Information) — la gravité seule n'est pas un signal de tri.",
      },
      {
        q: "Les fichiers .evtx volumineux sont-ils gérés ?",
        a: "L'analyse tourne dans un Web Worker. La mémoire croît avec la taille du fichier ; quelques centaines de Mo passent facilement dans un navigateur moderne. Pour les collections plus grosses, exportez avec evtx_dump et chargez par tranches.",
      },
    ],
  },
  footer: {
    blog: "Blog",
    builtWith:
      "Construit avec WebAssembly et le crate Rust omerbenamram/evtx. 100 % côté client — vos fichiers ne quittent jamais votre navigateur.",
  },
  notFound: {
    title: "404 — page introuvable",
    heading: "Page introuvable",
    description:
      "Cette URL n'existe pas sur ce site. Elle a peut-être été déplacée, ou vous avez suivi un lien obsolète.",
    backHome: "← Retour à l'accueil",
  },
  blog: {
    indexTitle: "Notes sur le journal d'événements",
    indexIntro:
      "Notes courtes sur le format binaire du journal d'événements Windows, les ID d'événements forensiquement utiles et les workflows de triage.",
    readMore: "Lire la suite",
    backToBlog: "← Retour au blog",
    publishedOn: "Publié le",
    updatedOn: "Mis à jour le",
    readingTime: "{n} min de lecture",
    prevPost: "← Article précédent",
    nextPost: "Article suivant →",
    relatedHeading: "Articles liés",
    resourcesHeading: "Ressources externes",
    byLine: "Par",
  },
  eventIds: {
    title: "Référence des Event ID Windows",
    intro:
      "Index sélectionné des Event ID Windows qui comptent en investigation forensique — groupés par canal, avec les champs EventData à lire en premier. Cliquez sur un ID couvert pour le guide détaillé ; les autres pointent vers Microsoft Learn.",
    description:
      "Index de référence des Event ID Windows utiles en DFIR : Security 4624/4625/1102, System 7045/7036, Sysmon 1/3/7/11, PowerShell 4104, TaskScheduler, Kerberos — avec liens vers nos guides détaillés.",
    columnId: "Event ID",
    columnName: "Nom",
    columnNotes: "Notes",
  },
  glossary: {
    title: "Glossaire du journal d'événements Windows",
    intro:
      "Les termes qui reviennent dans les enregistrements .evtx et les rapports DFIR, expliqués en une ou deux phrases.",
    description:
      "Définitions claires des termes du journal d'événements Windows : LogonType, BinXML, canal, provider, chunk, template, SID, EventData, RecordID, etc.",
  },
  tools: {
    title: "Outils EVTX comparés : KAPE, FTK Imager, wevtutil, evtx_dump",
    intro:
      "Comparaison côte à côte des outils utilisés en investigation Windows — ce que chacun fait vraiment bien, son coût et ses limites.",
    description:
      "Comparez KAPE, FTK Imager, wevtutil, evtx_dump, python-evtx, RawCopy et EVTX parser — par plateforme, cas d'usage, licence et limites. Choisissez le bon outil pour la collecte, l'analyse ou le triage en navigateur.",
    columnTool: "Outil",
    columnPlatform: "Plateforme",
    columnUseCase: "Cas d'usage principal",
    columnLicense: "Licence",
  },
  breadcrumb: {
    home: "Accueil",
    label: "Fil d'Ariane",
  },
  eventId: {
    title: "Event ID {id} : {name} ({channel})",
    intro:
      "Ce que cet Event ID enregistre vraiment sur disque, les champs EventData à lire en premier et sa place dans un workflow de triage DFIR.",
    description:
      "Windows Event ID {id} ({name}) sur le canal {channel} : signification, champs EventData, techniques offensives courantes et Event IDs liés.",
    channelLabel: "Canal",
    providerLabel: "Fournisseur",
    notesLabel: "Notes de triage",
    inDepthHeading: "Guide détaillé",
    inDepthCta: "Lire l'analyse complète",
    microsoftLearnHeading: "Microsoft Learn",
    microsoftLearnCta: "Ouvrir la référence officielle",
    relatedHeading: "Event IDs liés",
    notCoveredYet:
      "Cet Event ID figure dans l'index mais n'a pas encore d'analyse détaillée. Microsoft Learn couvre les champs au niveau du protocole.",
    notFoundTitle: "Event ID inconnu",
    notFoundDescription:
      "Cet Event ID ne figure pas encore dans l'index de référence.",
  },
  tags: {
    indexTitle: "Sujets — tous les tags du blog",
    indexIntro:
      "Tous les sujets couverts sur le blog, avec le nombre d'articles par tag. Utilisable comme second axe de navigation à côté de l'index Event ID.",
    indexDescription:
      "Parcourez les sujets du blog EVTX parser : audit Security, Sysmon, PowerShell, Kerberos, services, internes du format EVTX et collecte forensique.",
    tagTitleTemplate: "Articles taggés « {tag} »",
    tagIntroTemplate:
      "Tous les articles du blog taggés « {tag} », plus récents d'abord.",
    tagDescriptionTemplate:
      "Articles d'analyse Windows Event Log taggés « {tag } » — notes DFIR, techniques offensives et internes du parseur.",
    postsCount: "{n} articles",
    tagsOnPost: "Tags",
    labels: {
      security: "Audit Security",
      logon: "Logon",
      process: "Processus",
      account: "Compte",
      privileges: "Privilèges",
      "object-access": "Accès aux objets",
      kerberos: "Kerberos",
      "anti-forensics": "Anti-forensique",
      attack: "Techniques offensives",
      sysmon: "Sysmon",
      powershell: "PowerShell",
      system: "Canal System",
      service: "Service",
      persistence: "Persistance",
      format: "Format EVTX",
      fundamentals: "Fondamentaux",
      collection: "Collecte",
      tooling: "Outillage",
      navigation: "Navigation",
    },
  },
  toc: {
    heading: "Sur cette page",
  },
};
