import type { Dict } from "./types";

export const it: Dict = {
  meta: {
    title: "Visualizzatore EVTX online — aprire file .evtx senza upload",
    description:
      "Un file .evtx è un registro eventi di Windows. Aprilo gratis nel browser — senza upload né installazione — filtra ed esporta in CSV, TXT, JSON o XML.",
    siteName: "EVTX parser",
  },
  home: {
    heading: "EVTX parser",
    headline: "EVTX parser — visualizzatore di log eventi Windows nel browser",
    intro:
      "Trascina un log eventi .evtx di Windows. L'analisi viene eseguita interamente nel browser via WebAssembly — non viene caricato nulla.",
    featuredHeading: "Guide in evidenza",
    dropArea: "Trascina un .evtx qui o clicca per sceglierne uno",
    privacyNote: "I file restano sul tuo dispositivo. Analisi 100 % lato client.",
    statusReading: "Lettura di {name}…",
    statusParsing: "Analisi del log eventi…",
    eventsLabel: "eventi",
    filterPlaceholder: "Cerca in tutti i campi… es. mimikatz, EventID:4624 LogonType:10 -IpAddress:127.0.0.1",
    clearFilter: "Pulisci",
    noMatches: "Nessun evento corrisponde al filtro.",
    topIds: "ID frequenti",
    exportCsv: "Esporta CSV",
    exportJson: "Esporta JSON",
    exportTxt: "Esporta TXT",
    includeXml: "Colonna XML grezzo",
    exporting: "Esportazione…",
    clearTime: "Pulisci intervallo",
    clearAll: "Rimuovi tutto",
    clearFilters: "Cancella filtri",
    removeFile: "Rimuovi file",
    enterFullscreen: "Schermo intero",
    exitFullscreen: "Esci da schermo intero",
    whatIsHeading: "Cos'è un file EVTX?",
    whatIsBody:
      "Un file .evtx è un registro eventi di Windows — il formato binario che Windows usa da Vista per registrare eventi di sicurezza, di sistema e delle applicazioni. Si trovano in C:\\Windows\\System32\\winevt\\Logs (Security.evtx, System.evtx, Application.evtx…) e non sono testo semplice: il Blocco note non riesce a leggerli. Trascinane uno qui sotto per visualizzarlo.",
    whatIsMore: "Guida completa al formato EVTX",
  },
  viewer: {
    fields: "Campi",
    hideFields: "Nascondi campi",
    top: "Frequenti",
    rare: "Rari",
    filterValues: "Filtra valori…",
    showMore: "Mostra altro",
    showLess: "Mostra meno",
    addField: "Aggiungi un campo…",
    include: "Filtra per questo valore",
    exclude: "Escludi questo valore",
    remove: "Rimuovi",
    pivots: "Pivot",
    pivotTime: "±5 min attorno a questo evento",
    pivotLogon: "Stessa sessione di accesso",
    pivotProcess: "Stesso processo",
    syntaxHelp: "Sintassi di ricerca",
    helpFree: "Cerca in tutti i campi, EventData inclusi",
    helpField: "Campo uguale al valore",
    helpWildcard: "Carattere jolly *",
    helpNot: "Escludi con un - davanti",
    helpOr: "Uno dei termini",
    helpCompare: "Confronto numerico",
    helpPivot: "Tutti gli eventi di una sessione di accesso",
    helpProcess: "Immagine del processo o del padre (4688 o Sysmon)",
    noValues: "Nessun valore",
    suggestions: "Suggerimenti",
    description: "Descrizione",
    copy: "Copia",
    copied: "Copiato",
    copyJson: "Copia come JSON",
    copyXml: "Copia XML",
    timeZoneToggle: "Mostra gli orari in UTC o nel fuso orario locale",
    hunts: "Hunt",
    huntsHint: "Ricerche con un clic delle attività tipiche degli attaccanti. Conteggi sui file caricati.",
    catCredential: "Accesso alle credenziali",
    catLateral: "Movimento laterale",
    catPersistence: "Persistenza",
    catExecution: "Esecuzione",
    catEvasion: "Elusione delle difese",
    catInitial: "Accesso iniziale",
    catDiscovery: "Ricognizione",
    catImpact: "Impatto",
    huntsFilter: "Filtra hunt…",
    hitsOnly: "Solo hunt con risultati",
    eventsTab: "Eventi",
    sessionsTab: "Sessioni di accesso",
    sessionsHint: "Una riga per accesso, token UAC uniti. Clicca su una sessione per vederne tutti gli eventi.",
    sessionStart: "Accesso",
    sessionEnd: "Disconnessione",
    sessionDuration: "Durata",
    sessionUser: "Account",
    sessionType: "Tipo di accesso",
    sessionSource: "Origine",
    sessionAdmin: "Admin",
    sessionEvents: "Eventi",
    sessionActivity: "Attività",
    sessionOpen: "ancora aperta",
    sessionUnknownStart: "prima dell'inizio del log",
    showSystemSessions: "Mostra sessioni di sistema e di servizio",
    noSessions: "Nessuna sessione di accesso nei log caricati — le sessioni si basano sugli eventi Security 4624.",
    filesLabel: "file",
    fileLabel: "file",
    showFiles: "Mostra file",
    hideFiles: "Nascondi file",
    showControls: "Mostra rilevamenti e cronologia",
    hideControls: "Nascondi rilevamenti e cronologia",
    rangeTitle: "Intervallo di tempo",
    rangeFrom: "Da",
    rangeTo: "A",
    rangeApply: "Applica",
    rangeInvalid: "L'inizio deve precedere la fine",
    pinColumn: "Fissa colonna",
    unpinColumn: "Sblocca colonna",
    resizeColumn: "Trascina per ridimensionare · doppio clic per adattare al contenuto",
    resetColumns: "Ripristina colonne",
    saveSession: "Salva sessione",
    sessionSaved: "Sessione salvata",
    savingSession: "Salvataggio…",
    savedSessionsTitle: "Sessioni salvate su questo dispositivo",
    savedSessionsHint: "Salvate solo in questo browser (IndexedDB) — nulla viene caricato. Riprendi da dove avevi lasciato o eliminale.",
    resumeSession: "Riprendi",
    deleteSession: "Elimina",
    confirmDeleteSession: "Eliminare questa sessione salvata? Viene rimossa solo la copia memorizzata in questo browser: i tuoi file su disco non vengono toccati.",
    cancel: "Annulla",
    sessionName: "Nome della sessione",
    saveSessionTitle: "Salva questa sessione",
    saveSessionDescription: "Salvata solo in questo browser — nulla viene caricato. Una volta salvata, le modifiche vengono salvate automaticamente.",
    renameSessionTitle: "Rinomina sessione",
    renameSession: "Rinomina",
    saveAction: "Salva",
    deleteSessionTitle: "Eliminare la sessione salvata?",
    restoringSession: "Ripristino della sessione…",
    storageFull: "Spazio di archiviazione del browser insufficiente per salvare questi file.",
    autoSaved: "Salvataggio automatico",
    autoSaveHint: "Salvata in questo browser — le modifiche vengono salvate automaticamente. Clicca per salvare ora.",
    note: "Nota dell'analista",
    notePlaceholder: "Aggiungi una nota per il report…",
    report: "Report (.md)",
    reportTitle: "Report di indagine EVTX",
    reportGenerated: "Generato il",
    copyLink: "Copia il link di questa ricerca",
    linkCopied: "Link copiato",
  },
  fileLocation: {
    heading: "Dove trovare i file .evtx",
    intro:
      "Sul sistema di origine ogni canale del registro eventi è un file .evtx separato, tutti nella stessa cartella. I percorsi presuppongono la cartella di Windows predefinita, C:\\Windows (%SystemRoot%).",
    allChannels: "Cartella dei log — tutti i canali",
    vistaPlus: "Windows Vista / Server 2008+",
    archived:
      "Log archiviati (Archive-<canale>-<timestamp>.evtx, se l'archiviazione automatica è attiva)",
    legacy:
      "Formato legacy .evt (anche AppEvent.Evt, SysEvent.Evt) — non supportato qui",
    howToHeading: "Come ottenerlo",
    howTo: [
      "Il servizio EventLog tiene aperti i log attivi, quindi una copia normale fallisce. Da una shell amministratore, `wevtutil epl Security C:\\triage\\Security.evtx` esporta una copia pulita (solo il log attivo — i file Archive-* sono esclusi).",
      "Per copiare l'intera cartella così com'è: KAPE (`--target EventLogs`), FTK Imager o RawCopy — oppure leggerla offline da un'immagine E01 montata o da una copia shadow del volume (VSS).",
      "Ogni .evtx è autonomo, non servono file accessori. Un canale può essere reindirizzato: verificate il percorso reale con `wevtutil gl <canale>` (logFileName).",
    ],
    readMore: "Guida alla raccolta: 4 metodi a confronto",
    copy: "Copia percorso",
    copied: "Copiato",
  },
  table: {
    record: "Rec. #",
    time: "Ora (UTC)",
    level: "Livello",
    eventId: "Event ID",
    name: "Nome",
    summary: "Riepilogo",
    provider: "Provider",
    channel: "Canale",
    computer: "Computer",
    source: "Origine",
    viewDetails: "Dettagli",
    closeDetails: "Chiudi",
    eventData: "Dati evento",
    noEventData: "Nessun campo EventData per questo record.",
    showRawXml: "Mostra XML grezzo",
    hideRawXml: "Nascondi XML grezzo",
    prev: "prec.",
    next: "succ.",
  },
  levels: {
    critical: "Critico",
    error: "Errore",
    warning: "Avviso",
    info: "Informazione",
    verbose: "Dettagliato",
    unknown: "—",
  },
  filter: {
    advanced: "Filtri avanzati",
    addCondition: "Aggiungi condizione",
    addGroup: "Aggiungi gruppo",
    removeCondition: "Rimuovi condizione",
    removeGroup: "Rimuovi gruppo",
    and: "E",
    or: "O",
    reset: "Reimposta filtri",
    matchCount: "{count} eventi corrispondenti",
    eventDataKey: "Nome del campo",
    eventDataKeyPlaceholder: "es. TargetUserName",
    valuePlaceholder: "valore",
    fields: {
      level: "Livello",
      category: "Tipo di evento",
      eventId: "ID evento",
      provider: "Provider",
      channel: "Canale",
      computer: "Computer",
      file: "File di origine",
      eventName: "Nome evento",
      timestamp: "Ora",
      eventData: "Campo EventData",
    },
    ops: {
      contains: "contiene",
      notContains: "non contiene",
      equals: "è uguale a",
      notEquals: "è diverso da",
      startsWith: "inizia con",
      regex: "corrisponde a (regex)",
      exists: "è presente",
      empty: "è vuoto",
      eq: "=",
      neq: "≠",
      lt: "<",
      lte: "≤",
      gt: ">",
      gte: "≥",
      in: "è uno di",
      notIn: "non è nessuno di",
      before: "prima di",
      after: "dopo",
      between: "tra",
    },
    categories: {
      security: "Sicurezza",
      system: "Sistema",
      sysmon: "Sysmon",
      powershell: "PowerShell",
      defender: "Defender",
      appLocker: "AppLocker",
      taskScheduler: "Utilità di pianificazione",
      rdpLocal: "RDP (sessione locale)",
      rdpRemote: "RDP (connessione remota)",
      rdpCore: "RDP (core)",
      wmiActivity: "Attività WMI",
      firewall: "Firewall",
      bits: "BITS",
      smbServer: "Server SMB",
      smbClient: "Client SMB",
      wlan: "WLAN",
      other: "Altro",
    },
  },
  faq: {
    heading: "FAQ log eventi",
    items: [
      {
        q: "Cos'è un file EVTX?",
        a: "EVTX è il formato binario del log eventi di Windows introdotto con Windows Vista. Ogni .evtx è una sequenza di blocchi da 64 KB; ogni blocco contiene una tabella di template XML e un flusso di record che la referenziano. L'analisi ricostruisce l'XML completo di ogni evento.",
      },
      {
        q: "Dove si trovano i .evtx su Windows?",
        a: "I log attivi stanno in C:\\Windows\\System32\\winevt\\Logs. I tre principali in ambito forense sono Security.evtx (accessi, privilegi), System.evtx (driver, servizi) e Application.evtx (errori applicativi). I canali Sysmon e PowerShell sono di solito i più preziosi in incident response.",
      },
      {
        q: "Questo strumento carica il mio .evtx da qualche parte?",
        a: "No. L'analisi avviene in un Web Worker con un parser EVTX in Rust compilato in WebAssembly. Il file viene letto in memoria del browser e mai trasmesso. Disconnetti la rete per verificarlo.",
      },
      {
        q: "Cosa significa la colonna Livello?",
        a: "I livelli EVTX sono numerici: 1 Critico, 2 Errore, 3 Avviso, 4 Informazione, 5 Dettagliato. Microsoft colloca alcuni ID noti (es. Security 4625 = autenticazione fallita a livello Informazione) — la severità da sola non basta per il triage.",
      },
      {
        q: "Riesce a gestire .evtx molto grandi?",
        a: "L'analisi gira in un Web Worker. La memoria cresce con la dimensione del file; qualche centinaio di MB è comodo nei browser moderni. Per raccolte più grandi, esporta con evtx_dump e ricarica a tratti.",
      },
    ],
  },
  footer: {
    blog: "Blog",
    builtWith:
      "Realizzato con WebAssembly e il crate Rust omerbenamram/evtx. 100 % lato client — i file non lasciano mai il browser.",
  },
  notFound: {
    title: "404 — pagina non trovata",
    heading: "Pagina non trovata",
    description:
      "Questo URL non esiste su questo sito. Forse è stato spostato o stai seguendo un link non più valido.",
    backHome: "← Torna alla home",
  },
  blog: {
    indexTitle: "Note sul log eventi",
    indexIntro:
      "Note brevi sul formato binario del log eventi di Windows, sugli Event ID utili in forense e sui flussi di triage.",
    readMore: "Continua a leggere",
    backToBlog: "← Torna al blog",
    publishedOn: "Pubblicato",
    updatedOn: "Aggiornato",
    readingTime: "{n} min di lettura",
    prevPost: "← Articolo precedente",
    nextPost: "Articolo successivo →",
    relatedHeading: "Articoli correlati",
    resourcesHeading: "Risorse esterne",
    byLine: "Di",
  },
  eventIds: {
    title: "Riferimento Event ID di Windows",
    intro:
      "Indice curato degli Event ID di Windows utili in un caso forense — raggruppati per canale, con i campi EventData da leggere per primi. Gli ID coperti rimandano alla guida; gli altri a Microsoft Learn.",
    description:
      "Indice di riferimento degli Event ID di Windows utili in DFIR: Security 4624/4625/1102, System 7045/7036, Sysmon 1/3/7/11, PowerShell 4104, TaskScheduler, Kerberos — con link a guide approfondite.",
    columnId: "Event ID",
    columnName: "Nome",
    columnNotes: "Note",
  },
  glossary: {
    title: "Glossario del log eventi di Windows",
    intro:
      "I termini che compaiono nei record .evtx e nei report DFIR, spiegati in una o due frasi.",
    description:
      "Definizioni semplici dei termini chiave del log eventi di Windows: LogonType, BinXML, canale, provider, chunk, template, SID, EventData, RecordID, ecc.",
  },
  tools: {
    title: "Strumenti EVTX a confronto: KAPE, FTK Imager, wevtutil, evtx_dump",
    intro:
      "Confronto affiancato degli strumenti usati dagli analisti con il log eventi di Windows — cosa fa davvero bene ciascuno, quanto costa e dove fallisce.",
    description:
      "Confronto tra KAPE, FTK Imager, wevtutil, evtx_dump, python-evtx, RawCopy ed EVTX parser — per piattaforma, caso d'uso, licenza e limiti.",
    columnTool: "Strumento",
    columnPlatform: "Piattaforma",
    columnUseCase: "Caso d'uso principale",
    columnLicense: "Licenza",
  },
  breadcrumb: {
    home: "Home",
    label: "Breadcrumb",
  },
  eventId: {
    title: "Event ID {id}: {name} ({channel})",
    intro:
      "Cosa registra davvero questo Event ID su disco, i campi EventData da leggere per primi e dove si colloca in un workflow di triage DFIR.",
    description:
      "Windows Event ID {id} ({name}) sul canale {channel}: significato, campi EventData, tecniche offensive comuni ed Event ID correlati.",
    channelLabel: "Canale",
    providerLabel: "Provider",
    notesLabel: "Note di triage",
    inDepthHeading: "Guida approfondita",
    inDepthCta: "Leggi l'analisi completa",
    microsoftLearnHeading: "Microsoft Learn",
    microsoftLearnCta: "Apri la documentazione ufficiale",
    relatedHeading: "Event ID correlati",
    notCoveredYet:
      "Questo Event ID è nell'indice ma non ha ancora un'analisi approfondita. Microsoft Learn copre i campi a livello di protocollo.",
    notFoundTitle: "Event ID sconosciuto",
    notFoundDescription:
      "Questo Event ID non è ancora presente nell'indice di riferimento.",
  },
  tags: {
    indexTitle: "Argomenti — tutti i tag del blog",
    indexIntro:
      "Tutti gli argomenti trattati nel blog, con il numero di articoli per tag. Utile come secondo asse di navigazione accanto all'indice Event ID.",
    indexDescription:
      "Esplora gli argomenti del blog EVTX parser: audit Security, Sysmon, PowerShell, Kerberos, servizi, interni del formato EVTX e raccolta forense.",
    tagTitleTemplate: "Articoli con il tag «{tag}»",
    tagIntroTemplate:
      "Tutti gli articoli del blog con il tag «{tag}», dal più recente.",
    tagDescriptionTemplate:
      "Articoli di forense del log eventi di Windows con il tag «{tag}» — note DFIR, tecniche offensive e interni del parser.",
    postsCount: "{n} articoli",
    tagsOnPost: "Tag",
    labels: {
      security: "Audit Security",
      logon: "Logon",
      process: "Processo",
      account: "Account",
      privileges: "Privilegi",
      "object-access": "Accesso agli oggetti",
      kerberos: "Kerberos",
      "anti-forensics": "Anti-forense",
      attack: "Tecniche offensive",
      sysmon: "Sysmon",
      powershell: "PowerShell",
      system: "Canale System",
      service: "Servizio",
      persistence: "Persistenza",
      format: "Formato EVTX",
      fundamentals: "Fondamenti",
      collection: "Raccolta",
      tooling: "Strumenti",
      navigation: "Navigazione",
    },
  },
  toc: {
    heading: "In questa pagina",
  },
};
