import type { Dict } from "./types";

export const pt: Dict = {
  meta: {
    title: "Visualizador EVTX online — abrir arquivos .evtx sem upload",
    description:
      "Um arquivo .evtx é um log de eventos do Windows. Abra-o grátis no navegador — sem upload nem instalação — filtre e exporte para CSV, TXT, JSON ou XML.",
    siteName: "EVTX parser",
  },
  home: {
    heading: "EVTX parser",
    headline: "EVTX parser — visualizador de logs de eventos Windows no navegador",
    intro:
      "Solte um log de eventos .evtx do Windows. A análise roda inteiramente no navegador via WebAssembly — nada é enviado.",
    featuredHeading: "Guias em destaque",
    dropArea: "Solte o .evtx aqui ou clique para escolher",
    privacyNote: "Os arquivos ficam no seu dispositivo. Análise 100 % no cliente.",
    statusReading: "Lendo {name}…",
    statusParsing: "Analisando o log de eventos…",
    eventsLabel: "eventos",
    filterPlaceholder: "Pesquisar em todos os campos… ex. mimikatz, EventID:4624 LogonType:10 -IpAddress:127.0.0.1",
    clearFilter: "Limpar",
    noMatches: "Nenhum evento corresponde ao filtro.",
    topIds: "IDs frequentes",
    exportCsv: "Exportar CSV",
    exportJson: "Exportar JSON",
    exportTxt: "Exportar TXT",
    includeXml: "Coluna XML bruto",
    exporting: "Exportando…",
    clearTime: "Limpar intervalo",
    clearAll: "Limpar tudo",
    clearFilters: "Limpar filtros",
    removeFile: "Remover arquivo",
    enterFullscreen: "Tela cheia",
    exitFullscreen: "Sair da tela cheia",
    whatIsHeading: "O que é um arquivo EVTX?",
    whatIsBody:
      "Um arquivo .evtx é um log de eventos do Windows — o formato binário que o Windows usa desde o Vista para registrar eventos de segurança, sistema e aplicativos. Ficam em C:\\Windows\\System32\\winevt\\Logs (Security.evtx, System.evtx, Application.evtx…) e não são texto puro, então o Bloco de Notas não consegue lê-los. Solte um abaixo para visualizá-lo.",
    whatIsMore: "Guia completo do formato EVTX",
  },
  viewer: {
    fields: "Campos",
    hideFields: "Ocultar campos",
    top: "Frequentes",
    rare: "Raros",
    filterValues: "Filtrar valores…",
    showMore: "Mostrar mais",
    showLess: "Mostrar menos",
    addField: "Adicionar um campo…",
    include: "Filtrar por este valor",
    exclude: "Excluir este valor",
    remove: "Remover",
    pivots: "Pivô",
    pivotTime: "±5 min em torno deste evento",
    pivotLogon: "Mesma sessão de logon",
    pivotProcess: "Mesmo processo",
    syntaxHelp: "Sintaxe de pesquisa",
    helpFree: "Pesquisa em todos os campos, incluindo EventData",
    helpField: "Campo igual ao valor",
    helpWildcard: "Curinga *",
    helpNot: "Excluir com um - na frente",
    helpOr: "Qualquer um dos termos",
    helpCompare: "Comparação numérica",
    helpPivot: "Todos os eventos de uma sessão de logon",
    helpProcess: "Imagem do processo ou do pai (4688 ou Sysmon)",
    noValues: "Sem valores",
    suggestions: "Sugestões",
    description: "Descrição",
    copy: "Copiar",
    copied: "Copiado",
    copyJson: "Copiar como JSON",
    copyXml: "Copiar XML",
    timeZoneToggle: "Mostrar horários em UTC ou no seu fuso horário",
    hunts: "Hunts",
    huntsHint: "Pesquisas em um clique de atividades comuns de atacantes. Contagens sobre os arquivos carregados.",
    catCredential: "Acesso a credenciais",
    catLateral: "Movimento lateral",
    catPersistence: "Persistência",
    catExecution: "Execução",
    catEvasion: "Evasão de defesas",
    catInitial: "Acesso inicial",
    catDiscovery: "Descoberta",
    catImpact: "Impacto",
    huntsFilter: "Filtrar hunts…",
    hitsOnly: "Somente hunts com resultados",
    note: "Nota do analista",
    notePlaceholder: "Adicionar uma nota ao relatório…",
    report: "Relatório (.md)",
    reportTitle: "Relatório de investigação EVTX",
    reportGenerated: "Gerado em",
    copyLink: "Copiar link desta pesquisa",
    linkCopied: "Link copiado",
  },
  fileLocation: {
    heading: "Onde encontrar os arquivos .evtx",
    intro:
      "No sistema de origem, cada canal do log de eventos é um arquivo .evtx separado, todos na mesma pasta. Os caminhos assumem a pasta padrão do Windows, C:\\Windows (%SystemRoot%).",
    allChannels: "Pasta de logs — todos os canais",
    vistaPlus: "Windows Vista / Server 2008+",
    archived:
      "Logs arquivados (Archive-<canal>-<timestamp>.evtx, se o arquivamento automático estiver ativo)",
    legacy:
      "Formato legado .evt (também AppEvent.Evt, SysEvent.Evt) — não suportado aqui",
    howToHeading: "Como obter",
    howTo: [
      "O serviço EventLog mantém os logs ativos abertos, então uma cópia comum falha. Num shell de administrador, `wevtutil epl Security C:\\triage\\Security.evtx` exporta uma cópia limpa (apenas o log ativo — arquivos Archive-* ficam de fora).",
      "Para copiar a pasta inteira como está: KAPE (`--target EventLogs`), FTK Imager ou RawCopy — ou leia offline a partir de uma imagem E01 montada ou de uma cópia de sombra de volume (VSS).",
      "Cada .evtx é autocontido, sem arquivos complementares. Um canal pode estar redirecionado: confirme o caminho real com `wevtutil gl <canal>` (logFileName).",
    ],
    readMore: "Guia de coleta: 4 métodos comparados",
    copy: "Copiar caminho",
    copied: "Copiado",
  },
  table: {
    record: "Reg. #",
    time: "Hora (UTC)",
    level: "Nível",
    eventId: "Event ID",
    name: "Nome",
    summary: "Resumo",
    provider: "Provedor",
    channel: "Canal",
    computer: "Computador",
    source: "Origem",
    viewDetails: "Detalhes",
    closeDetails: "Fechar",
    eventData: "Dados do evento",
    noEventData: "Este registro não tem campos EventData.",
    showRawXml: "Mostrar XML bruto",
    hideRawXml: "Ocultar XML bruto",
    prev: "ant.",
    next: "próx.",
  },
  levels: {
    critical: "Crítico",
    error: "Erro",
    warning: "Aviso",
    info: "Informação",
    verbose: "Detalhado",
    unknown: "—",
  },
  filter: {
    advanced: "Filtros avançados",
    addCondition: "Adicionar condição",
    addGroup: "Adicionar grupo",
    removeCondition: "Remover condição",
    removeGroup: "Remover grupo",
    and: "E",
    or: "OU",
    reset: "Redefinir filtros",
    matchCount: "{count} eventos correspondentes",
    eventDataKey: "Nome do campo",
    eventDataKeyPlaceholder: "ex. TargetUserName",
    valuePlaceholder: "valor",
    fields: {
      level: "Nível",
      category: "Tipo de evento",
      eventId: "ID de evento",
      provider: "Provedor",
      channel: "Canal",
      computer: "Computador",
      file: "Arquivo de origem",
      eventName: "Nome do evento",
      timestamp: "Data/hora",
      eventData: "Campo EventData",
    },
    ops: {
      contains: "contém",
      notContains: "não contém",
      equals: "é igual a",
      notEquals: "é diferente de",
      startsWith: "começa com",
      regex: "corresponde a (regex)",
      exists: "está presente",
      empty: "está vazio",
      eq: "=",
      neq: "≠",
      lt: "<",
      lte: "≤",
      gt: ">",
      gte: "≥",
      in: "é um de",
      notIn: "não é nenhum de",
      before: "antes de",
      after: "depois de",
      between: "entre",
    },
    categories: {
      security: "Segurança",
      system: "Sistema",
      sysmon: "Sysmon",
      powershell: "PowerShell",
      defender: "Defender",
      appLocker: "AppLocker",
      taskScheduler: "Agendador de Tarefas",
      rdpLocal: "RDP (sessão local)",
      rdpRemote: "RDP (conexão remota)",
      rdpCore: "RDP (núcleo)",
      wmiActivity: "Atividade WMI",
      firewall: "Firewall",
      bits: "BITS",
      smbServer: "Servidor SMB",
      smbClient: "Cliente SMB",
      wlan: "WLAN",
      other: "Outro",
    },
  },
  faq: {
    heading: "FAQ logs de eventos",
    items: [
      {
        q: "O que é um arquivo EVTX?",
        a: "EVTX é o formato binário do log de eventos do Windows introduzido no Windows Vista. Cada .evtx é uma sequência de blocos de 64 KB; cada bloco contém uma tabela de templates XML e um fluxo de registros que a referenciam. A análise reconstrói o XML completo de cada evento.",
      },
      {
        q: "Onde encontro .evtx no Windows?",
        a: "Os logs ativos ficam em C:\\Windows\\System32\\winevt\\Logs. Os três principais para forense são Security.evtx (logons, privilégios), System.evtx (drivers, serviços) e Application.evtx (erros de aplicação). Os canais Sysmon e PowerShell costumam ser os mais valiosos em resposta a incidentes.",
      },
      {
        q: "Esta ferramenta envia meu .evtx para algum lugar?",
        a: "Não. A análise acontece em um Web Worker usando um parser EVTX em Rust compilado para WebAssembly. O arquivo é lido na memória do navegador e nunca transmitido. Desligue a rede se quiser verificar.",
      },
      {
        q: "O que significa a coluna Nível?",
        a: "Os níveis EVTX são numéricos: 1 Crítico, 2 Erro, 3 Aviso, 4 Informação, 5 Detalhado. A Microsoft atribui alguns IDs conhecidos (ex.: Security 4625 = falha de autenticação no nível Informação) — só a severidade não basta para triagem.",
      },
      {
        q: "Aguenta arquivos .evtx muito grandes?",
        a: "A análise roda em um Web Worker. A memória escala com o tamanho; algumas centenas de MB são confortáveis em navegadores modernos. Para coleções maiores, exporte com evtx_dump e recarregue em partes.",
      },
    ],
  },
  footer: {
    blog: "Blog",
    builtWith:
      "Feito com WebAssembly e o crate Rust omerbenamram/evtx. 100 % no cliente — seus arquivos não saem do navegador.",
  },
  notFound: {
    title: "404 — página não encontrada",
    heading: "Página não encontrada",
    description:
      "Essa URL não existe neste site. Talvez tenha sido movida, ou você seguiu um link antigo.",
    backHome: "← Voltar ao início",
  },
  blog: {
    indexTitle: "Notas sobre logs de eventos",
    indexIntro:
      "Notas curtas sobre o formato binário do log de eventos do Windows, Event IDs úteis em forense e fluxos de triagem.",
    readMore: "Leia mais",
    backToBlog: "← Voltar ao blog",
    publishedOn: "Publicado",
    updatedOn: "Atualizado",
    readingTime: "{n} min de leitura",
    prevPost: "← Anterior",
    nextPost: "Próximo →",
    relatedHeading: "Posts relacionados",
    resourcesHeading: "Recursos externos",
    byLine: "Por",
  },
  eventIds: {
    title: "Referência de Event ID do Windows",
    intro:
      "Índice curado dos Event ID do Windows que importam em um caso forense — agrupados por canal, com os campos EventData mais úteis. IDs cobertos vão para o guia detalhado; os demais para o Microsoft Learn.",
    description:
      "Índice de referência dos Event ID do Windows úteis em DFIR: Security 4624/4625/1102, System 7045/7036, Sysmon 1/3/7/11, PowerShell 4104, TaskScheduler, Kerberos — com links para guias detalhados.",
    columnId: "Event ID",
    columnName: "Nome",
    columnNotes: "Notas",
  },
  glossary: {
    title: "Glossário do log de eventos do Windows",
    intro:
      "Os termos que aparecem nos registros .evtx e nos relatórios DFIR, explicados em uma ou duas frases.",
    description:
      "Definições claras dos termos do log de eventos do Windows: LogonType, BinXML, canal, provider, chunk, template, SID, EventData, RecordID etc.",
  },
  tools: {
    title: "Ferramentas EVTX comparadas: KAPE, FTK Imager, wevtutil, evtx_dump",
    intro:
      "Comparação lado a lado das ferramentas usadas por analistas com o log de eventos do Windows — para que cada uma é boa, quanto custa e onde falha.",
    description:
      "Compare KAPE, FTK Imager, wevtutil, evtx_dump, python-evtx, RawCopy e EVTX parser — por plataforma, caso de uso, licença e limitações.",
    columnTool: "Ferramenta",
    columnPlatform: "Plataforma",
    columnUseCase: "Caso de uso principal",
    columnLicense: "Licença",
  },
  breadcrumb: {
    home: "Início",
    label: "Trilha de migalhas",
  },
  eventId: {
    title: "Event ID {id}: {name} ({channel})",
    intro:
      "O que esse Event ID realmente registra em disco, os campos EventData a ler primeiro e onde ele se encaixa em um fluxo de triagem DFIR.",
    description:
      "Windows Event ID {id} ({name}) no canal {channel}: significado, campos EventData, técnicas ofensivas comuns e Event IDs relacionados.",
    channelLabel: "Canal",
    providerLabel: "Provedor",
    notesLabel: "Notas de triagem",
    inDepthHeading: "Guia detalhado",
    inDepthCta: "Ler a análise completa",
    microsoftLearnHeading: "Microsoft Learn",
    microsoftLearnCta: "Abrir a referência oficial",
    relatedHeading: "Event IDs relacionados",
    notCoveredYet:
      "Este Event ID está no índice mas ainda não tem uma análise detalhada. O Microsoft Learn cobre os campos no nível do protocolo.",
    notFoundTitle: "Event ID desconhecido",
    notFoundDescription:
      "Este Event ID ainda não consta no índice de referência.",
  },
  tags: {
    indexTitle: "Tópicos — todas as tags do blog",
    indexIntro:
      "Todos os tópicos cobertos no blog, com o número de posts por tag. Use como segunda camada de navegação ao lado do índice de Event ID.",
    indexDescription:
      "Navegue pelos tópicos do blog EVTX parser: auditoria Security, Sysmon, PowerShell, Kerberos, serviços, internos do formato EVTX e coleta forense.",
    tagTitleTemplate: "Posts com a tag «{tag}»",
    tagIntroTemplate:
      "Todos os posts do blog com a tag «{tag}», dos mais recentes primeiro.",
    tagDescriptionTemplate:
      "Posts de forense do log de eventos do Windows com a tag «{tag}» — notas DFIR, técnicas ofensivas e internos do parser.",
    postsCount: "{n} posts",
    tagsOnPost: "Tags",
    labels: {
      security: "Auditoria Security",
      logon: "Logon",
      process: "Processo",
      account: "Conta",
      privileges: "Privilégios",
      "object-access": "Acesso a objetos",
      kerberos: "Kerberos",
      "anti-forensics": "Anti-forense",
      attack: "Técnicas ofensivas",
      sysmon: "Sysmon",
      powershell: "PowerShell",
      system: "Canal System",
      service: "Serviço",
      persistence: "Persistência",
      format: "Formato EVTX",
      fundamentals: "Fundamentos",
      collection: "Coleta",
      tooling: "Ferramentas",
      navigation: "Navegação",
    },
  },
  toc: {
    heading: "Nesta página",
  },
};
